services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      retries: 5
      timeout: 10s
    ports:
      - 5432:5432

  # migrator:
  #   build:
  #     context: .
  #   environment:
  #     - SQL_DRIVER=postgres
  #     - SQL_HOST=postgres
  #     - SQL_PORT=5432
  #     - SQL_USER=admin
  #     - SQL_PASSWORD=admin
  #     - SQL_DB=test
  #     - SQL_DB_SCHEMA=aaron
  #     - SQL_SSL=disable
  #     - MIGRATION_DIR=/go/bin/migrations
  #     - MIGRATION_TABLE=migrations
  #     - MIGRATION_SCHEMA=platform
  #   volumes:
  #     - ./migrations:/go/bin/migrations
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
