name: Go Build Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"

      - name: Move Version File
        run: make move-version

      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.22.1
          dest: build
          prefix: migoro
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          x: true
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.MIGORO_TOKEN }}
        run: gh release create ${{ github.ref_name }} ./build/* --title ${{ github.ref_name }} --notes '${{ steps.extract-release-notes.outputs.release_notes }}'
