name: Go Build Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Go Generate
        run: make generate

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

      - name: Install Changelog Lint
        run: make install-changelog-lint

      - name: Changelog Lint
        run: make changelog-lint

      - name: Version Lint
        run: make version-lint

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"

      - name: Go Compile
        run: make ci-build

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.MIGORO_TOKEN }}
        run: gh release create ${{ github.ref_name }} ./build/* --title ${{ github.ref_name }} --notes '${{ steps.extract-release-notes.outputs.release_notes }}'
