name: Go Build Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"

      - name: Compile
        run: make ci-build

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.MIGORO_TOKEN }}
        run: gh release create ${{ github.ref_name }} ./build/* --title ${{ github.ref_name }} --notes '${{ steps.extract-release-notes.outputs.release_notes }}'
